apiVersion: v1
kind: ReplicationController
metadata:
  labels:
    name: openam
  name: openam
spec:
  replicas: 1
  selector:
    name: openam
  template:
    metadata:
      labels:
         name: openam
         site: site1
    spec:
      containers:
      - name: git-sync
        image: gcr.io/google_containers/git-sync
        volumeMounts:
          - name: config
            mountPath: /config
        env:
          - name: GIT_SYNC_REPO
            value: https://github.com/ForgeRock/stack-config.git
          - name: GIT_SYNC_DEST
            value: /config
          - name: GIT_SYNC_WAIT
            value: "60"
      - name: openam
        image: wstrange/openam-nightly
        ports:
          - name: openam
            containerPort: 8080
        volumeMounts:
          - name: openam-root
            mountPath: /root/openam
          - name: secrets
            mountPath: /secrets
          - name: config
            mountPath: /config
      volumes:
        - name: secrets
          secret:
            secretName: fr-secrets
        - name: openam-root
          emptyDir: {}
        - name: config
          emptyDir: {}
