apiVersion: v1beta3
kind: ReplicationController
metadata:
  labels:
    name: openama
  name: openama
spec:
  replicas: 1
  selector:
    name: openam-a
  template:
    metadata:
      labels:
         name: openam-a
         site: site1
    spec:
      containers:
      - name: openam-a
        image: wstrange/openam-nightly
        env:
          - name: "OPENAM_INSTANCE"
            value: "openam01"
# Does a port need a name?
        ports:
        - name: openam-8080
          containerPort: 8080
          protocol: TCP
#        volumeMounts:
#        - name: openam-a
#          mountPath: /root/openam
#          readOnly: false
#      volumes:
#      - name: openam-a
#        nfs:
#          server: 172.17.8.1
#          path: "/Users/warren/Downloads/persist/openam-a"
#          readOnly: false
