apiVersion: v1beta3
kind: Service
metadata:
  name: openam-b
  label:
    - name: openam-b
spec:
  ports:
    - port: 9080
      targetPort: 8080
      protocol: "TCP"
  publicIPs:
#    - 172.17.8.102
    - 10.245.1.3
  selector:
    name: openam-b
