apiVersion: v1beta3
kind: ReplicationController
metadata:
  labels:
    name: openamb
  name: openamb
spec:
  replicas: 1
  selector:
    name: openam-b
  template:
    metadata:
      labels:
         name: openam-b
         site: site1
    spec:
      containers:
      - name: openam-b
        image: wstrange/openam-nightly
        env:
          - name: "OPENAM_INSTANCE"
            value: "openam01"
        ports:
        - name: openam-8080
          containerPort: 8080
          protocol: TCP
#        volumeMounts:
#        - name: openam-b
#          mountPath: /root/openam
#          readOnly: false
#      volumes:
#      - name: openam-b
#        nfs:
#          server: 172.17.8.1
#          path: "/Users/warren/Downloads/persist/openam-b"
#          readOnly: false
