apiVersion: v1beta3
kind: Service
metadata:
  name: haproxy
  labels:
    name: haproxy
spec:
  ports:
    - port: 80
      targetPort: http
      protocol: "TCP"
      name: http-80
  createExternalLoadBalancer: true
  sessionAffinity: ClientIP
  selector:
    name: haproxy