# Job that loads policies
apiVersion: extensions/v1beta1
kind: Job
metadata:
  name: amconfig
spec:
  selector:
    matchLabels:
      app: amconfig
  template:
    metadata:
      name: amconfig
      labels:
        app: amconfig
    spec:
      containers:
      - name: git-sync
        image: gcr.io/google_containers/git-sync
        volumeMounts:
          - name: config
            mountPath: /config
        env:
          - name: GIT_SYNC_REPO
            value: https://github.com/ForgeRock/stack-config.git
          - name: GIT_SYNC_DEST
            value: /config
          - name: GIT_SYNC_BRANCH
            value: master
          - name: GIT_SYNC_WAIT
            value: "120"
      - name: amconfig
        image: wstrange/amconfig:latest
        env:
          - name: OPENAM_URL
            value: "http://openam:80/openam"
          - name: OPENAM_USER
            value: amadmin
          - name: OPENAM_PW_FILE
            value: /secrets/amadmin.pw
        volumeMounts:
          - name: config
            mountPath: /config
          - name: secrets
            mountPath: /secrets
      restartPolicy: Never
      volumes:
        - name: secrets
          secret:
            secretName: fr-secrets
        - name: config
          emptyDir: {}
