apiVersion: extensions/v1beta1
kind: Job
metadata:
  name: ssoconfig
spec:
  selector:
    matchLabels:
      app: ssoconfig
  template:
    metadata:
      name: ssoconfig
      labels:
        app: ssoconfig
    spec:
      containers:
      - name: git-sync
        image: gcr.io/google_containers/git-sync
        volumeMounts:
          - name: config
            mountPath: /config
        env:
          - name: GIT_SYNC_REPO
            value: https://github.com/ForgeRock/stack-config.git
          - name: GIT_SYNC_DEST
            value: /config
          - name: GIT_SYNC_WAIT
            value: 60
      - name: ssoconfig
        image: wstrange/ssoconfig-nightly:latest
        volumeMounts:
          - name: config
            mountPath: /config
      restartPolicy: Never
      volumes:
        - name: secrets
          secret:
        - name: config
          emptyDir: {}
