apiVersion: v1
kind: Service
metadata:
  name: openam-svc
  labels:
    name: openam-svc
spec:
  type: NodePort
  ports:
    - port: 80
      targetPort: openam
      protocol: TCP
      name: http
      nodePort: 30080
  selector:
    site: site1