---
# Configure OpenAM on base image

- hosts: localhost
  connection: local
  tasks:
  - name: Configure Primary OpenAM instance
    ssoconfigure: server_url="{{item}}"
      deployment_uri="/openam"
      base_dir="/tmp/openam"
      directory_server="opendj.local"
      root_suffix="o=openam"
      directory_admin_port="4444"
      directory_jmx_port="1689"
      directory_port="1389"
      ds_dirmgrdn="cn=Directory Manager"
      data_store="dirServer"
      ds_dirmgrpasswd="password"
      amldapuserpasswd="Passw0rd"
      userstore_type="LDAPv3ForOpenDS"
      userstore_ssl="SIMPLE"
      userstore_host="opendj.local"
      userstore_port="1389"
      userstore_mgrdn="cn=Directory Manager"
      userstore_passwd="password"
      userstore_suffix="dc=example,dc=com"
      cookie_domain=".acme.com"
      admin_pwd="password"
      acceptlicense="true"
      am_enc_key="AQICY6Za5J5noktyqnhW10JiPVNUdKuiZYwS"
      lb_site_name="sitea"
      lb_primary_url="http://openam.acme.com:80/openam"
      lb_session_ha_sfo="true"
    with_items:
      - http://openam.acme.com:9080/